name: Bug report
description: Report a problem
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Steps to reproduce, expected vs. actual
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: If known, include the commit SHA or tag
